// This file is automatically generated. Do not edit it directly.
import { createClient } from '@supabase/supabase-js';
import type { Database } from './types';

const SUPABASE_URL = import.meta.env.VITE_SUPABASE_URL;
const SUPABASE_PUBLISHABLE_KEY = import.meta.env.VITE_SUPABASE_PUBLISHABLE_KEY;

// Import the supabase client like this:
// import { supabase } from "@/integrations/supabase/client";

// Dynamic storage adapter: uses localStorage when "remember me" is enabled, otherwise sessionStorage
const REMEMBER_KEY = 'sb-remember';
const chooseStorage = () => {
  try {
    const remembered = localStorage.getItem(REMEMBER_KEY) === 'true';
    return remembered ? localStorage : sessionStorage;
  } catch {
    return localStorage;
  }
};

const dynamicStorage = {
  getItem: (key: string) => chooseStorage().getItem(key),
  setItem: (key: string, value: string) => chooseStorage().setItem(key, value),
  removeItem: (key: string) => chooseStorage().removeItem(key),
};

export const supabase = createClient<Database>(SUPABASE_URL, SUPABASE_PUBLISHABLE_KEY, {
  auth: {
    storage: dynamicStorage as Storage,
    persistSession: true,
    autoRefreshToken: true,
  }
});
